name: Changelog

on:
  pull_request:
    types: [closed]

  release:
    types: [published]

  issues:
    types: [closed, edited]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v1

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ github.token }}

      - name: Git commit, rebase onto master, push
        env:
          PUSH_BRANCH: master
          TMP_BRANCH: ${{ github.repository }}${{ github.run_id}}
        run: |
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR"
          git checkout -b $TMP_BRANCH
          git status
          git add CHANGELOG.md
          git commit -m 'Updated CHANGELOG.md' 
          git fetch
          git status
          git checkout -b $PUSH_BRANCH --track origin/${PUSH_BRANCH}
          git rebase $TMP_BRANCH $PUSH_BRANCH
          git status
          git push
