name: Create Release from Version Tags

on:
  push:
    tags: ["v*"]

jobs:
  build:
    name: Build Release
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-22.04

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

      - name: Set up REPO and TAG environment vars
        run: |
          echo "REPO=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_SHA:0:6}" >> $GITHUB_ENV

      - name: This run was triggered by a version tag, reset the $TAG variable to the tag name
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Create GitHub release
        if: ${{ contains(github.ref, 'refs/tags/') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${TAG}
