name: Test Coverage

on: push

jobs:
  build:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-22.04

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run test suite
        run: npm run test

      # # The Coveralls repo token is found  on the project's Settings page
      # - name: Upload to Coveralls
      #   env:
      #     COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      #     COVERALLS_RUN_LOCALLY: yes
      #   run: |
      #     composer require 'php-coveralls/php-coveralls:2.5.2'
      #     vendor/bin/php-coveralls \
      #       --coverage_clover coverage/clover.xml \
      #       --json_path ./coveralls-upload.json \
      #       --verbose

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage to Codecov
        # https://github.com/codecov/codecov-action
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          files: coverage/clover.xml
          verbose: true

      # The Code Climate Test Coverage Reporter ID can be found by visiting the project's
      # Repo Settings pane, click Test Coverage in the left sidebar. Find the ID in the
      # second section.
      - name: Code Climate coverage
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          debug: true
          coverageLocations: |
            coverage/clover.xml:clover
